[package]
name = "mgmm"
version = "0.1.0"
authors = ["David Li <li.davidm96@gmail.com>"]

[dependencies]
cgmath = "0.7"
gfx = "0.12"
gfx_window_glutin = "0.12"
glutin = "0.6"
gfx_device_gl = "0.11"
time = "0.1"